// Generated by scripts/contract-gen.mjs - do not edit.
// Regenerate: pnpm contract:gen [--url <openapi.json url>]

/** The ora contract version (spec info.version) these types were generated from. */
export const BUILT_AGAINST = "1.25.0";
